import assert from 'node:assert/strict';
import { shortSector, shortInitial, receivableType, receivablePayment } from '../frontend/js/components/financial-labels.js';
import { renderActionTable } from '../frontend/js/components/renderers.js';
assert.equal(receivableType('MENSALIDADE'), 'MEN...');
assert.equal(receivableType('ACOLHIMENTO'), 'ACO...');
assert.equal(receivableType('OUTRO', {setor_nome: 'Administração'}), 'ADM');
assert.equal(shortSector('Administração'), 'ADM');
for (const [value, expected] of [['PARTICULAR','P'],['SOCIAL','S'],['CONVENIO','C'],['VARIAVEL','V'],['FIXA','F']]) assert.equal(shortInitial(value), expected);
const row = {status:'PARCIAL', saldo_restante:100, data_vencimento:'2000-01-01'};
assert.equal(receivablePayment(row.status,row,'2026-09-25'),'ATRASO');
assert.equal(receivablePayment('PAGA',{...row,saldo_restante:0}),'PAGA');
assert.equal(receivablePayment('ABERTA',{...row,data_vencimento:'2026-09-25'},'2026-09-25'),'ABERTA');
const html = renderActionTable([row], [['Pagamento','status',receivablePayment]],()=> '');
assert.match(html,/status--danger">ATRASO/);
assert.match(html,/data-status="ATRASO"/);
console.log('Abreviações e indicação vermelha de atraso, inclusive pagamento parcial, aprovadas.');
